// <auto-generated />
namespace Blog6ITN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AanpassingModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AanpassingModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100950526_AanpassingModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
